services:
  # PostgreSQL database
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Kratos migrations service
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    depends_on:
      - postgres
    environment:
      - DSN=postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable
    volumes:
      - ./docker/kratos/config:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - app_network

  # Ory Kratos - Identity and User Management
  kratos:
    image: oryd/kratos:v1.3.1
    depends_on:
      - postgres
      - mailslurper
      - kratos-migrate
    ports:
      - "4433:4433" # public API
      - "4434:4434" # admin API
    environment:
      - DSN=postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable
    volumes:
      - ./docker/kratos/config:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - app_network

  # MailSlurper for email testing
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436" # Web UI
      - "4437:4437" # API
      - "1025:1025" # SMTP
    networks:
      - app_network

  # Sample UI with Kratos Auth
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:4433/
      - SECURITY_MODE=
      - COOKIE_SECRET=32-BYTES-LONG-COOKIE-SECRET-VALUE-32
      - CSRF_COOKIE_NAME=__Host-csrf
      - CSRF_COOKIE_SECRET=32-BYTES-LONG-CSRF-SECRET-VALUE-123
    networks:
      - app_network
    depends_on:
      - kratos

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
